lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/posts", PostController
    resources "/userfollows", FollowingController
    post "/session", SessionController,  :login
    delete "/sessions", SessionController, :logout

#    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", MicroblogWeb do
  #   pipe_through :api
  # end
end

lib/microblog_web/views/layout_view.ex
defmodule MicroblogWeb.LayoutView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Microblog!</title>
    <link rel="stylesheet" href="/css/app-c74cbb59dd9f0e78c2a9064258aa52b7.css?vsn=d">
  </head>

  <body>
    +   <nav class="navbar navbar-dark bg-dark navbar-expand-md">
       <a class="navbar-brand" href="#">Microblog</a>
 
       <button class="navbar-toggler" type="button"
               data-toggle="collapse" data-target="#main-navbar">
         <span class="navbar-toggler-icon"></span>
       </button>
 
       <div class="collapse navbar-collapse" id="main-navbar">
         <ul class="navbar-nav mr-auto">
           <li class="nav-item">
         <%= link "Posts", to: post_path(@conn, :index), class: "nav-link" %>
     </li>
     <li class="nav-item">
               <%= link "Users", to: user_path(@conn, :index), class: "nav-link" %>
 
           </li>
         </ul>
       </div>

      <%= if @current_user do %>
         <span class="text-light">
           <%= @current_user.email %> |
           <%= link("logout", to: session_path(@conn, :logout), method: :delete) %>
         </span>
       <% else %>
         <%= form_for @conn, session_path(@conn, :login), 
               [as: "user", class: "form-inline w-75"], fn f -> %>
           <input type="text" placeholder="email" 
                              class="form-control" name="email">
           <input type="submit" value="Log in" class="btn btn-primary">
         <% end %>
       <% end %>
    </nav>
<!--    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

  <%= if get_flash(@conn, :info) do %>
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <% end %>
  <%= if get_flash(@conn, :error) do %>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

      <%= link "Posts", to: post_path(@conn, :index), class: "nav-link" %>


    </div> --><!-- /container -->

      <div class="row">
        <div class="col-sm-12 my-2">
          <%= if get_flash(@conn, :info) do %> 
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error) do %> 
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
          <% end %>
        </div>
      </div>
 
      <div class="row">
        <div class="col-sm-8">
          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>
 
    </div> <!-- container -->
 
    <!--<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>-->

    <script src="/js/app-ef692c8485fb52a34461461c56ca282a.js?vsn=d"></script>
  </body>
</html>